mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^weather_byte_app/', include('weather_byte_app.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import include,url

from . import views

app_name = "polls"
urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$',views.ResultsView.as_view(),name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
]

mysite/weather_byte_app/urls.py
from django.conf.urls import include,url

from . import views

app_name = "weather_byte_app"
urlpatterns = [
    url(r'^$',views.landingPage,name='landingPage'),
    url(r'^register/$',views.register,name='register'),
    url(r'^(?P<error>[0-9]+)/register/$',views.register,name='register'),
    url(r'^login/$',views.login,name='login'),
    url(r'^(?P<user_id>[0-9]+)/homepage/$',views.homepage,name='homepage'),
    url(r'^(?P<user_id>[0-9]+)/ten_day/$', views.ten_day,name='ten_day'),
]

mysite/weather_byte_app/models.py
# -*- coding: utf-8 -*-
from __future__   import unicode_literals
from django.db    import models
from django.utils import timezone
import json
import requests

my_dict   = {}
response  = requests.get("http://api.wunderground.com/api/3140b82d0c92e7ea/geolookup/q/South_Africa.json")
weather   = response.json()
my_dict["city"] = weather.get('response').get('results')
my_list = my_dict.get('city')
my_city_list = []

for city in my_list:
    my_city_list.append(city.get('city'))

my_city_list.append('Cape Town')
my_city_list.sort()
my_city_list.insert(0,'Auto')

CITIES = [(x,x) for x in my_city_list]

class MyUsers(models.Model):
    user_username   = models.CharField(max_length=20)
    user_email      = models.CharField(max_length=20)
    user_password   = models.CharField(max_length=200)
    user_first_name = models.CharField(max_length=20)
    user_last_name  = models.CharField(max_length=100)
    user_location   = models.CharField(max_length=200,choices=CITIES)
    user_apps       = models.CharField(max_length=100)
    pub_date        = models.DateTimeField('Registered Date')

    def __str__(self):
        return self.user_username
    
    

class Weather(models.Model):
    app_code = models.CharField(max_length=100,default = "1")
    user_id  = models.ForeignKey(MyUsers, on_delete=models.CASCADE, default=1)
    weather_type_code = models.CharField(max_length=3,default="trdw")
    weather_area      = models.CharField(max_length=100)
    weather_date      = models.DateField('Published Date')

    class Meta:
        indexes = [
            models.Index(fields=['app_code','user_id','weather_date','weather_area','weather_type_code'], name = 'idxw1'),
        ]

    def __str__(self):
        return str(self.weather_type_code) + " " + str(self.weather_date)
    
class Weather_Component(models.Model):
    weather_id               = models.ForeignKey(Weather,on_delete=models.CASCADE,default=1)
    weather_comp_datetime    = models.CharField(max_length=200)
    weather_comp_icon_url    = models.CharField(max_length=200)
    weather_comp_min_temp    = models.CharField(max_length=10)
    weather_comp_max_temp    = models.CharField(max_length=10)
    weather_comp_rain        = models.CharField(max_length=100)
    weather_comp_description = models.CharField(max_length=200)
    weather_comp_label       = models.CharField(max_length=100)

    class Meta:
        indexes = [
            models.Index(fields=['weather_id','weather_comp_datetime'],name='idxwc1'),
            ]
    

mysite/weather_byte_app/forms.py
from django import forms
from weather_byte_app.models import MyUsers
from django.forms import ModelForm
import json
import requests

class RegistrationForm(ModelForm):

    class Meta:
        model = MyUsers
        fields = ['user_username','user_email','user_password',
                  'user_first_name','user_last_name','user_location']
        widgets = {
        'user_password': forms.PasswordInput(),
        }
        labels = {
        'user_username': 'Username','user_email':'Email Address',
        'user_password':'Password','user_first_name':'First Name',
        'user_last_name':'Last Name','user_location':'Location'
        }
        
class LoginForm(ModelForm):
    class Meta:
        model = MyUsers
        fields = ['user_username','user_password']
        widgets = {
        'user_password': forms.PasswordInput(),
        }
        labels = {
            'user_username':'Username','user_password':'Password'
            }

mysite/weather_byte_app/views.py
# -*- coding: utf-8 -*-
from __future__       import unicode_literals
from django.http      import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404,render
from .models          import MyUsers,Weather,Weather_Component
from django.template  import loader
from django.http      import Http404
from django.urls      import reverse
from django.views     import generic
from django.utils     import timezone
from .forms           import RegistrationForm,LoginForm
from passlib.hash     import pbkdf2_sha256
from django           import forms
from datetime import date,datetime
import json
import requests
import datetime

my_city_list = []

def ten_day(request,user_id):
    try:
        user = MyUsers.objects.get(pk=user_id)
    except MyUsers.DoesNotExist:
        return HttpResponseRedirect(reverse('weather_byte_app:register',args=(1,)))
    else:
        ten_day_weather  = Weather.objects.get(app_code="1",user_id=user,weather_date=date.today(),weather_area=user.user_location,weather_type_code="10dw")
        weather_list_one = Weather_Component.objects.filter(weather_id=ten_day_weather)[0:5]
        weather_list_two = Weather_Component.objects.filter(weather_id=ten_day_weather)[5:10]
        return render (request, 'weather_byte_app/ten_day.html',{'weather_list_one':weather_list_one,'weather_list_two':weather_list_two,'user':user})

def homepage(request, user_id,page=0):
    user_location=""
    today_date = date.today()
    try:
        user = MyUsers.objects.get(pk=user_id)
    except MyUsers.DoesNotExist:
        return HttpResponseRedirect(reverse('weather_byte_app:register',args=(1,)))
    else:
        if user.user_location == "Auto":
           response        = request.get("http://api.wunderground.com/api/3140b82d0c92e7ea/geolookup/q/autopip.json")
           location        = response.json()
           user_location = weather.get('response').get('results').get('city')
        else:
            user_location = user.user_location
        try:
            check_data      = Weather.objects.get(weather_date=today_date,user_id=user)
        except (Weather.DoesNotExist):
            new_weather_three_day = Weather(app_code="1",user_id = user,weather_type_code="03dw",weather_area=user_location,weather_date=today_date)
            new_weather_ten_day   = Weather(app_code="1",user_id = user,weather_type_code="10dw",weather_area=user_location,weather_date=today_date)
            new_weather_three_day.save()
            new_weather_ten_day.save()
            response        = requests.get("http://api.wunderground.com/api/3140b82d0c92e7ea/forecast/q/South_Africa/" + user_location + ".json")
            weather         = response.json()
            weather_list    = weather.get('forecast').get('simpleforecast').get('forecastday')
            for period in weather_list:
                minimum      = period.get('low').get('celsius')
                maximum      = period.get('high').get('celsius')
                icon         = period.get('icon_url')
                rain         = period.get('qpf_allday').get('mm')
                description  = period.get('conditions')
                today_datetime = datetime.datetime.today()
                weather_comp = Weather_Component(weather_id = new_weather_three_day,weather_comp_datetime=today_datetime,
                                                 weather_comp_icon_url = icon,weather_comp_min_temp = minimum,weather_comp_max_temp = maximum,
                                                 weather_comp_rain = rain,weather_comp_description = description)
                weather_comp.save()
                
            response_ten      = requests.get("http://api.wunderground.com/api/3140b82d0c92e7ea/forecast10day/q/South_Africa/" + user_location + ".json")
            weather_ten      = response_ten.json()
            weather_list_ten = weather_ten.get("forecast").get("simpleforecast").get("forecastday")
            for period in weather_list_ten:
                minimum = period.get('low').get('celsius')
                maximum = period.get('high').get('celsius')
                icon    = period.get('icon_url')
                rain    = period.get('qpf_allday').get('mm')
                weather_day_name = period.get('date').get('weekday')
                weather_day      = period.get('date').get('day')
                weather_month    = period.get('date').get('monthname_short')
                weather_year     = period.get('date').get('year')
                weather_date     = "{} {} {} {}".format(weather_day_name,weather_day,weather_month,weather_year)
                description      = "NA"
                weather_comp  = Weather_Component(weather_id = new_weather_ten_day,weather_comp_datetime=weather_date,
                                                 weather_comp_icon_url = icon,weather_comp_min_temp = minimum,weather_comp_max_temp = maximum,
                                                 weather_comp_rain = rain,weather_comp_description = description)
                weather_comp.save()
        except(Weather.MultipleObjectsReturned):
            a = ""
        today_weather = Weather.objects.get(app_code="1",user_id=user,weather_date=date.today(),weather_area=user.user_location,weather_type_code="03dw")
        weather_list  = Weather_Component.objects.filter(weather_id=today_weather)[0]
        user = MyUsers.objects.get(pk=user_id)
        return render (request, 'weather_byte_app/homepage.html',{'weather_list':weather_list,'user':user})

def landingPage(request):
    form = LoginForm()
    return render(request, 'weather_byte_app/login.html',{'form':form})

def register(request,error=0):
    form      = RegistrationForm()
    if error != 0:
        return render(request, 'weather_byte_app/registration.html', {'form':form,'error_message':"Something has gone wrong.",})
    else:
        return render(request, 'weather_byte_app/registration.html',{'form':form})

def login(request):
    try:
        if request.POST["register"] != "":
            form = RegistrationForm(request.POST)
            if form.is_valid():
                new_user=form.save(commit=False)
                try:
                    selected_user = MyUsers.objects.get(user_username = new_user.user_username)
                except MyUsers.DoesNotExist:
                    hash = pbkdf2_sha256.encrypt(new_user.user_password, rounds=200000, salt_size=16)
                    new_user = MyUsers(user_username = new_user.user_username,user_email=new_user.user_email,user_password=hash,
                                       user_first_name=new_user.user_first_name,user_last_name=new_user.user_last_name,
                                       user_location=new_user.user_location,user_apps='1',pub_date=timezone.now())
                    new_user.save()
                    return HttpResponseRedirect(reverse('weather_byte_app:homepage',args=(new_user.pk,)))
                else:
                    return render(request, 'weather_byte_app/registration.html', {'form':form,'error_message':"A user with the user Name " + str(name) + " already exists",})
            else:
                return render(request,'weather_byte_app/registration.html', {'form':form,'error_message':"Something went wrong",})
    except KeyError:
            form     = LoginForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                try:
                    current_user = MyUsers.objects.get(user_username = user.user_username)
                except MyUsers.DoesNotExist:
                    return render(request, 'weather_byte_app/login.html', {'form':form,'error_message':"Invalid login details"})
                else:
                    hash = current_user.user_password
                    if pbkdf2_sha256.verify(user.user_password, hash) == True:
                        return HttpResponseRedirect(reverse('weather_byte_app:homepage',args=(current_user.pk,)))
                    else:
                        return render(request, 'weather_byte_app/login.html', {'form':form,'error_message':"Invalid password"})
            else:
               return render(request, 'weather_byte_app/login.html', {'error_message':"Something has gone wrong"})

mysite/weather_byte_app/templates/weather_byte_app/homepage.html
<html>
<head>

{% load static %}

<style>
	
	
</style>

<link rel="stylesheet" href="{% static 'weather_byte_app/bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'weather_byte_app/style.css' %}"   />
<meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body class="body-login">

	<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<a class="navbar-brand" href= "">Home</a>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'weather_byte_app:ten_day' user_id=user.pk %}">10-day Forecast<span class="sr-only">(current)</span></a>
			</li>
		</ul>
	</div>
	</nav>
	
	<div class="container-fluid">
		<div class="text-center">
					<h1> Welcome  {{ user.user_first_name }} {{ user.user_last_name }} </h1>
					<h2> Today's weather </h2>
					<div class=" card card-outline-success col-2 offset-md-5 mt-5 ">
					<div> Min Temp:{{ weather_list.weather_comp_min_temp  }} C° </div> 
					<div> Max Temp:{{ weather_list.weather_comp_max_temp }} C° </div> 
					<div> Rain Today: {{ weather_list.weather_comp_rain  }}mm </div> 
					<div> Weather: {{ weather_list.weather_comp_description }} </div>
					<div> <img src = {{ weather_list.weather_comp_icon_url  }} alt = "Weather icon"> </div>
					</div>
		</div>
	</div>
</body>
</html>

mysite/weather_byte_app/templates/weather_byte_app/landing.html
<h1> Weather Byte App </h1>

<form action="{% url 'weather_byte_app:register' %}" method="post">
{% csrf_token %}

	<button type="submit" name="register" value = '1'> Register</button>
	<button type="submit" name="login" value = '2'   > Login </button>
	
</form>

mysite/weather_byte_app/templates/weather_byte_app/login.html
<head>

{% load static %}

<style>
	
	ul {
	display:none
    }
	
	p {
	margin:0;
	padding:0;
	}
	
	a {
	margin:0;
	padding:0;
	}
	
</style>

<link rel="stylesheet" href="{% static 'weather_byte_app/bootstrap/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'weather_byte_app/style.css' %}"   />

</head>
<body class="body-login">
	<div class="container">
		<div class="row">
			<div class="col-4 offset-md-4 bg-primary mt-5 rounded-5 text-center">
				<div class="col-2 offset-md-2 pt-5" >
					<h1> Login </h1>
					{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}

					<form action ="{% url 'weather_byte_app:login' %}" method=post>
					{% csrf_token %}
						{{ form.as_p }}
						<input type="submit" name="login" value = "Login" class="btn-primary"></input>
					</form>
					
				</div>
				<p> Don't have an account yet?<br/> <a class="text-success" href = "{% url 'weather_byte_app:register' %}"> Register here </a> </p>
			</div>
		</div>
	</div>
</body>

mysite/weather_byte_app/templates/weather_byte_app/registration.html
<head>

{% load static %}

<style>
	
	ul {
	display:none
    }
	
	label {
	width:200px;
	display:inline-block;
	text-align:left;
	}
</style>

<link rel="stylesheet" href="{% static 'weather_byte_app/bootstrap/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'weather_byte_app/style.css' %}"   />
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body class="body-login">
	<div class="container-fluid">
		<div class="row justfiy-content-start">
			<div class="col-4 offset-md-4 bg-primary mt-5 rounded-5 text-center">
				<div class="col-2 offset-md-2 pt-5" >
					<h1> Registration </h1>
					{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}
					<form action ="{% url 'weather_byte_app:login' %}" method=post>
					{% csrf_token %}
					{{ form.as_p }}
					<input type="submit" name="register" value = "Register" class="btn-primary"></input>
				</div>
			</div>
		</div>
	</div>
</body>

mysite/weather_byte_app/templates/weather_byte_app/ten_day.html
<html>
<head>

{% load static %}



<link rel="stylesheet" href="{% static 'weather_byte_app/bootstrap/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'weather_byte_app/style.css' %}"   />
<meta name="viewport" content="width=device-width, initial-scale=1">

<style>
	.card {
		background-color: rgb(255,255,255);
		}
	
	
</style>

</head>

<body class="body-login">

	<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
	<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<a class="navbar-brand" href="{% url 'weather_byte_app:homepage' user_id=user.pk %}">Home</a>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'weather_byte_app:ten_day' user_id=user.pk %}">10-day Forecast<span class="sr-only">(current)</span>
					
				</a>
			</li>
		</ul>
	</div>
	</nav>
	
	<div class="container-fluid">
		<div class="text-center">
					<h1> Welcome  {{ user.user_first_name }} {{ user.user_last_name }} </h1>
					<h2> Today's weather </h2>
					<div class = "col-10 row offset-md-2">
					{% for weather in weather_list_one %}
					<div class=" card card-outline-success col-2">
					<div>          {{ weather.weather_comp_datetime  }}    </div>
					<div> Min Temp:{{ weather.weather_comp_min_temp  }} C° </div> 
					<div> Max Temp:{{ weather.weather_comp_max_temp }} C°  </div> 
					<div> Rain Today: {{ weather.weather_comp_rain  }}mm   </div> 
					<div> <img src = {{ weather.weather_comp_icon_url  }} alt = "Weather icon"> </div>
					</div>
					{% endfor %}
					</div>
					<div class = "col-10 row offset-md-2">
					{% for weather in weather_list_two %}
					<div class=" card card-outline-success col-2">
					<div>          {{ weather.weather_comp_datetime  }}    </div>
					<div> Min Temp:{{ weather.weather_comp_min_temp  }} C° </div> 
					<div> Max Temp:{{ weather.weather_comp_max_temp }} C°  </div> 
					<div> Rain Today: {{ weather.weather_comp_rain  }}mm   </div> 
					<div> <img src = {{ weather.weather_comp_icon_url  }} alt = "Weather icon"> </div>
					</div>
					{% endfor %}
					</div>
					
		</div>
	</div>
</body>
</html>